"""initial schema

Revision ID: 0d1355d0cf27
Revises: 
Create Date: 2026-01-23 13:44:33.890076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d1355d0cf27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_journal', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('published_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True))
    op.drop_column('articles', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('articles', 'published_date')
    op.drop_column('articles', 'published_journal')
    # ### end Alembic commands ###
