"""routes done

Revision ID: 1e108c10ab5d
Revises: 0d1355d0cf27
Create Date: 2026-01-23 18:58:44.300749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e108c10ab5d'
down_revision: Union[str, Sequence[str], None] = '0d1355d0cf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_names', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author_names')
    # ### end Alembic commands ###
