"""initial models

Revision ID: 02c527a529d7
Revises: 
Create Date: 2026-01-25 20:33:43.820279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c527a529d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('institute', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published_journal', sa.String(), nullable=True),
    sa.Column('published_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('author_names', sa.String(), nullable=False),
    sa.Column('corresponding_author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corresponding_author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'author_id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('cited_from_id', sa.Integer(), nullable=False),
    sa.Column('cited_to_id', sa.Integer(), nullable=False),
    sa.Column('if_key_reference', sa.Boolean(), nullable=False),
    sa.Column('if_secondary_reference', sa.Boolean(), nullable=False),
    sa.Column('citation_content', sa.String(), nullable=True),
    sa.Column('ai_rated_score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('author_comment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cited_from_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['cited_to_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('references')
    op.drop_table('author_article')
    op.drop_table('articles')
    op.drop_table('authors')
    # ### end Alembic commands ###
