"""make feedback and author_comment nullable

Revision ID: 0c3921bf6d02
Revises: 02c527a529d7
Create Date: 2026-01-25 20:47:39.621789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3921bf6d02'
down_revision: Union[str, Sequence[str], None] = '02c527a529d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('references', 'author_comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'author_comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('references', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
