"""Add id column to AuthorArticle

Revision ID: 54f88c68fac8
Revises: d4669549e498
Create Date: 2026-01-26 15:32:10.495639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f88c68fac8'
down_revision: Union[str, Sequence[str], None] = 'd4669549e498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_article_article_id_fkey'), 'author_article', type_='foreignkey')
    op.drop_constraint(op.f('author_article_author_id_fkey'), 'author_article', type_='foreignkey')
    op.create_foreign_key(None, 'author_article', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'author_article', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_article', type_='foreignkey')
    op.drop_constraint(None, 'author_article', type_='foreignkey')
    op.create_foreign_key(op.f('author_article_author_id_fkey'), 'author_article', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('author_article_article_id_fkey'), 'author_article', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
