"""add article subject and keywords

Revision ID: 5811e6a86696
Revises: 9cbda3dbcabc
Create Date: 2026-01-28 19:46:04.605965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5811e6a86696'
down_revision: Union[str, Sequence[str], None] = '9cbda3dbcabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('keywords', sa.String(), nullable=True))
    op.alter_column('authors', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('articles', 'keywords')
    op.drop_column('articles', 'subject')
    # ### end Alembic commands ###
