"""add password to Author and login routes

Revision ID: 9cbda3dbcabc
Revises: 86a36f7dd06b
Create Date: 2026-01-27 11:34:19.668061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbda3dbcabc'
down_revision: Union[str, Sequence[str], None] = '86a36f7dd06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('authors', sa.Column('password', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'password')
    # ### end Alembic commands ###
