"""remodel routes

Revision ID: a2ec2300d90d
Revises: e590df2e5da3
Create Date: 2026-01-26 13:19:55.229516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ec2300d90d'
down_revision: Union[str, Sequence[str], None] = 'e590df2e5da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_article', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('author_article', 'author_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_article', sa.Column('author_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('author_article', 'id')
    # ### end Alembic commands ###
