"""Add cascade delete to AuthorArticle

Revision ID: e590df2e5da3
Revises: 0c3921bf6d02
Create Date: 2026-01-26 11:54:07.854054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e590df2e5da3'
down_revision: Union[str, Sequence[str], None] = '0c3921bf6d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_article_author_id_fkey'), 'author_article', type_='foreignkey')
    op.drop_constraint(op.f('author_article_article_id_fkey'), 'author_article', type_='foreignkey')
    op.create_foreign_key(None, 'author_article', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_article', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_article', type_='foreignkey')
    op.drop_constraint(None, 'author_article', type_='foreignkey')
    op.create_foreign_key(op.f('author_article_article_id_fkey'), 'author_article', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(op.f('author_article_author_id_fkey'), 'author_article', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
